# Generated by Django 3.0.7 on 2023-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Grado', models.CharField(max_length=25)),
                ('Materia', models.CharField(max_length=70)),
                ('Nombre', models.CharField(max_length=70)),
                ('Nom_archivo_ubi', models.CharField(max_length=70)),
                ('Serie', models.CharField(max_length=70)),
                ('Peso', models.CharField(max_length=15)),
                ('Ubicacion', models.CharField(max_length=30)),
                ('Ruta', models.CharField(max_length=70)),
            ],
        ),
    ]
